export const  _e = {
    fa: {
        ///////////// START UP ////////////////
        slogan:"خرید ارزان، آسان و هوشندانه",
        signup:"عضویت",
        already_member:"قبلا عضو شده اید؟",
        login:"وارد شوید",
        powered_by:"با پشتیبانی شرکت MatesPack استرالیا",
        ///////////// SIGN UP ////////////////
        fullname:"نام و نام خانوادگی",
        mobile:"شماره موبایل",
        password:"رمز عبور",
        optional_email:"ایمیل (اختیاری)",
        referrer:"کد معرف (اختیاری)",
        register:"ثبت مشخصات",
        accept_terms:"ثبت نام به منزله پذیرش شرایط و مقررات استفاده می باشد.",
        terms:"شرایط و مقررات استفاده",
        privacy:"سیاست حفظ حریم شخصی کاربران",
        ///////////// SIGN IN ////////////////
        forgot_password:"رمز عبورم را فراموش کرده ام",
        not_member:"حساب کاربری ندارید؟",
        become_member:"عضو شوید",
        get_code:"دریافت کد تایید",
        get_code_text:"",
        confirm_code:"تایید شماره موبایل",
        confirm:"تایید",
        confirm_text_line_top:"پیامکی شامل یک کد 5 رقمی به شماره موبایل",
        confirm_text_line_bottom:"ارسال شد. شما حدود 5 دقیقه زمان دارید که این کد را در اینجا وارد و شماره موبایل خود را تایید نمایید.",
        /////////////DRAWER////////////////
        current_store:"فروشگاه انتخابی",
        view_profile:"مشاهده پروفایل",
        view_store:"مشاهده فروشگاه",
        change_store:"تغییر فروشگاه",
        set_location:"انتخاب محل روی نقشه",
        notifications:"پیام ها",
        basket:"سبد خرید",
        orders_history:"تاریخچه سفارشات",
        free_credit:"اعتبار خرید رایگان",
        special_offers:"حراج جمعه بازار",
        customer_support:"پشتیبانی",
        settings:"تنظیمات",
        /////////////STORE HOME////////////////
        store_details: "مشخصات فروشگاه",
        view_store_products:"مشاهده همه کالاهای فروشگاه",
        working_hours:"ساعات سرویس دهی",
        free_delivery:"سرویس رایگان",
        delivery_area:"محدوده سرویس دهی",
        delivery_time:"زمانبندی ارسال سفارش",
        distance:"فاصله تا شما",
        view_categories:" قفسه های فروشگاه (دسته بندی ها)",
        view_offers:"کالاهای تخفیف دار",
        stores_nearby:"فروشگاههای اطراف شما",
        store_address:'آدرس فروشگاه',
        open:"باز است",
        closed:"بسته است",
        select_store:"انتخاب فروشگاه",
        /////////////HOME////////////////
        buy_from:"خرید از",
        /////////////MAP///////////////
        where_are_you:"کجا هستید؟",
        your_location:"محدوده دریافت سفارش",
        /////////////VIEW PRODUCT///////////////
        based_on:"بر اساس",
        reviews:"نظر",
        discount:"تخفیف",
        currency:"تومان",
        compare_price:"مقایسه قیمت این کالا در بازار",
        compare_price_description:" قیمت ارائه شده صرفا بر اساس قیمت فروش کالا می باشد و ممکن است فروشگاههای دیگر شرایط تحویل و کیفیت خدمات متفاوتی را داشته باشند که تصمیم نهایی خرید با توجه به عوامل مختلف به عهده خریدار می باشد.",
        customer_reviews:"نظرات مشتریان فروشگاه",
        about_seller:"درباره فروشنده",
        shop_is_closed:"فروشگاه در حال حاضر بسته است. سفارش شما پس از باز شدن فروشگاه ارسال خواهد شد",
        shop_is_open:"فروشگاه باز است و ارسال سفارشات بر اساس زمان درخواستی شما ارسال می شود.",
        description:"توضیحات",
        shipment_info:"زمانبندی فرستادن سفارش",
        buy:"خـریــد",
        view_product:"مشاهده کالا",
    },

    en: {
        ///////////// START UP ////////////////
        slogan:"Smarter way of shopping",
        signup:"Sign Up",
        already_member:"Already a Member?",
        login:"Login",
        powered_by:"Powered by: MatesPack Australia",
        ///////////// SIGN UP ////////////////
        fullname:"Full Name",
        mobile:"Mobile Number",
        password:"Password",
        optional_email:"Email", // Email (Optional)
        referrer:"Referrer (Optional)",
        register:"Register",
        accept_terms:"I accept all terms and conditions.",
        terms:"Terms & Conditions",
        privacy:"Privacy Policy",
        ///////////// SIGN IN ////////////////
        forgot_password:"Forgot your password?",
        not_member:"Not a member?",
        become_member:"Become a Member",
        get_code:"Get Code",
        get_code_text:"",
        confirm_code:"Confirm Code",
        confirm:"Confirm",
        confirm_text_line_top:"We just sent you a 5 digits code to ",
        confirm_text_line_bottom:"Please confirm the code here within 5 minutes.",
        /////////////DRAWER////////////////
        current_store:"Current Store",
        view_profile:"View Profile",
        view_store:"View Store",
        change_store:"Change Store",
        set_location:"Set Location on Map",
        notifications:"Notifications",
        basket:"View Basket",
        orders_history:"Orders History",
        free_credit:"Free Shopping",
        special_offers:"Special Offers",
        customer_support:"Customer Support",
        settings:"Settings",
        /////////////STORE HOME////////////////
        store_details:'Store Details',
        view_store_products:"View Store Products",
        working_hours:"Working Hours",
        free_delivery:"Free Delivery",
        delivery_area:"Delivery Area",
        delivery_time:"Average Delivery Time",
        distance:"Distance",
        view_categories:"View Store Categories",
        view_offers:"View Offers",
        stores_nearby:"Stores Around You",
        store_address:'Address',
        open:"Open",
        closed:"Closed",
        select_store:"Select Store",
        /////////////HOME////////////////
        buy_from:"Store:",
        /////////////MAP///////////////
        where_are_you:"Set Your Location",
        your_location:"Your Location",
        /////////////SETTINGS///////////////
        edit_profile:"Edit Profile",
        fav_addresses:"Favorite Addresses",
        help:"Help",
        logout:"Logout",
        /////////////VIEW PRODUCT///////////////
        based_on:"Based on",
        reviews:"Reviews",
        discount:"Discount",
        currency:"USD",
        compare_price:"Price Compare",
        compare_price_description:"price compare description comes here",
        customer_reviews:"Customer Reviews",
        about_seller:"About Seller",
        shop_is_closed:"The store is closed",
        shop_is_open:"The store is open",
        description:"Description",
        shipment_info:"Shipment Info",
        buy:"Add to Cart",
        view_product:"Product Details",
    }
}